language: ruby
rvm:
  - 1.9.2
  - 1.9.3
gemfile: Gemfile.ci
bundler_args: --without development guard pry airbrake
env:
  - DB=postgres
  - DB=sqlite
  - DB=mysql
before_script:
  - bundle exec rake ci:setup --trace
matrix:
  allow_failures:
    - rvm: 1.9.3
    - env: DB=mysql