language: ruby
rvm:
  - 1.9.3
  - 2.0.0
gemfile: Gemfile.ci
bundler_args: --without development guard pry airbrake
env:
  - DB=postgres
  - DB=sqlite
before_script:
  - bundle exec rake ci:setup --trace
matrix:
  allow_failures:
  - rvm: 2.0.0
