language: ruby
rvm:
  - 1.9.3
gemfile: Gemfile.ci
bundler_args: --without development guard pry airbrake
env:
  - DB=postgres
#  - DB=sqlite BUNDLE_WITHOUT=mysql:postgres
#  - DB=mysql BUNDLE_WITHOUT=sqlite:postgres
before_script:
  - bundle exec rake ci:setup --trace
